""" Encode any known changes to the database here
to help the matching process
"""

renamed_modules = {
    # OCA/product-attribute
    'product_m2m_categories': 'product_multi_category',
    # OCA/e-commerce
    'product_links': 'product_multi_link',
    # OCA/sale-workflow
    'sale_exceptions': 'sale_exception',
    # OCA/partner-contact
    'partner_external_maps': 'partner_external_map',
    'partner_relations': 'partner_multi_relation',
    # OCA/server-tools
    'disable_openerp_online': 'disable_odoo_online',
    'inactive_session_timeout': 'auth_session_timeout',
    # OCA/runbot-addons
    'runbot_secure': 'runbot_relative',
    # not exactly a module rename, but they do the same
    'account_check_writing': 'account_check_printing',
    # same here, whoever want this will also need bank-payment
    'account_payment': 'account_payment_order',
    # OCA/account-invoicing
    'account_refund_original': 'account_invoice_refund_link',
    # 'l10n_ar_invoice': 'l10n_ar_account',
    # 'l10n_ar_base_vat': 'l10n_ar_partner',
    # OCA/social
    'marketing_security_group': 'mass_mailing_security_group',
    # ADHOC RENAMES
    'l10n_ar_invoice': 'account_document',
    'l10n_ar_partner_title': 'l10n_ar_partner',
    'l10n_ar_chart_generic': 'l10n_ar_chart',
    'l10n_ar_account_vat_ledger_city': 'l10n_ar_account_vat_ledger_citi',
    'l10n_ar_invoice_sale': 'l10n_ar_sale',
    'account_invoice_journal_filter': 'account_invoice_journal_group',
    'account_contract_lines_sequence': 'sale_contract_lines_sequence',
    'account_contract_prices_update': 'sale_contract_prices_update',
    'account_voucher_withholding': 'account_withholding',
    'account_voucher_withholding_automatic': 'account_withholding_automatic',
    # 'product_supplier_search': 'product_supplier_usability',
    # TODO ACTIVAR, todavia no lo queremos
    'l10n_ar_aeroo_voucher': 'l10n_ar_aeroo_payment_group',
    'purchase_uom_prices_uoms': 'product_purchase_uom',
    'product_template_search_by_ean13': 'product_template_search_by_barcode',
    'website_sale_l10n_ar_partner': 'l10n_ar_website_sale',
    'account_move_analytic': 'account_move_line_analytic_filters',
    'product_category_search': 'product_category_full_name_search',
    'account_analytic_purchase_contract': 'purchase_contract',
    # no podemos porque en realidad deberiamos borrar antes el anterior
    # si hacemos merge
    # 'stock_product_move': 'stock_usability',
    # OCA
    # odoomrp/odoomrp-wip
    'document_page_work_instructions': 'document_page_work_instruction',
    'mgmtsystem_manuals': 'mgmtsystem_manual',
    'product_variants_no_automatic_creation': 'product_variant_configurator',
    'sale_product_variants': 'sale_variant_configurator',
    'sale_stock_product_variants': 'sale_stock_variant_configurator',
    'purchase_product_variants': 'purchase_variant_configurator',
    # OCA/account-payment - Module merged in OCA/account-financial-tools
    # da error y no lo usamos
    # 'account_payment_term_multi_day': 'account_payment_term_extension',
    # OCA/account-financial-reporting
    'account_financial_report_webkit': 'account_financial_report_qweb',
    # OCA/contract
    'account_analytic_analysis': 'contract',
    # OCA/website
    'website_disable_odoo': 'website_odoo_debranding',
}

renamed_models = {
}

# TODO this has been moved to addons/obsolte_modules.py
# obsolte_modules = [
#     # web_widget_color
#     # PENDING MIGRATION
#     'sale_multiple_invoice',
#     'auth_admin_passkey',
#     'account_move_voucher',
#     'account_tax_settlement',
#     'account_tax_settlement_withholding',
#     'hr_sign_in_out_task',
#     'website_sale_note',
#     'web_widget_one2many_tags',
#     'portal_fix',
#     'report_aeroo_portal_fix',
#     'portal_partner_fix',
#     'account_journal_book',
#     # 'web_export_view', ya instalable
#     'web_advanced_search_wildcard',
#     'web_advanced_search_x2x',
#     'web_search_with_and',
#     'web_favicon',
#     'website_favicon',
#     'website_server_mode',
#     # Verificar compatibilidad con enterprie
#     'web_sheet_full_width',
#     'web_switch_company_warning',

#     # 'website_talkus', no deberia hacer falta borrar
#     'report_custom_filename',
#     'auth_brute_force',
#     'mass_mailing_statistic_extra',
#     'admin_useful_groups',
#     # 'web_widget_float_formula', ya instalable
#     # 'web_widget_many2many_tags_multi_selection', ya instalable
#     # 'web_widget_x2many_2d_matrix', ya instalable
#     # 'web_widget_color', ya instalable

#     # REPLACED, CHECK DATA IS NOT LOST
#     'l10n_ar_bank_cbu',
#     'product_computed_price_rule',
#     'project_task_desc_html',
#     # OBSOLETE (this module has no problem to loose data)
#     # modulos que sacabamos antes de mandar a migrar a odoo
#     'sale_usability_extension',
#     'stock_usability',
#     'web_shortcuts',
#     'website_mail_snippet_table_edit',
#     'bi_view_editor',
#     'web_action_close_wizard_view_reload',
#     'mis_builder_demo',
#     'ir_export_extended_ept',
#     'web_clean_navbar',
#     'attachment_edit',
#     'attachment_preview',
#     'contract_show_invoice',
#     'sale_usability_extension',
#     # 'support_branding',
#     'web_ir_actions_act_window_message',
#     'web_recipients_uncheck',
#     'web_cleditor_ept',
#     'web_graph_sort',
#     # 'contract_discount',
#     # 'web_dashboard_tile',
#     'web_easy_switch_company',
#     'adhoc_base_setup',
#     'purchase_prices_update',
#     'timesheet_task',
#     'hr_timesheet_task',
#     # 'disable_openerp_online',
#     'cron_run_manually',
#     'project_task_delegate',
#     'account_analytic_project',
#     'project_category',
#     # modulos anteriores
#     'purchase_line_defaults',
#     'report_xls',
#     'account_analytic_analysis_mods',
#     'purchase_product_menu',
#     'l10n_ar_account_followup',
#     'account_journal_sequence',
#     'account_allow_code_change',
#     'account_contract_recurring_total',
#     'product_bookstore',
#     'account_transfer',
#     'account_consolidation_company',
#     'account_general_ledger_fix',
#     'account_move_line_no_filter',
#     'account_onchange_fix',
#     'account_partner_account_summary',
#     'account_partner_balance',
#     'account_financial_report_webkit_xls',
#     'account_statement_disable_invoice_import',
#     'account_statement_move_import',
#     'multi_store',
#     'portal_account_summary',
#     'account_multicompany_usability_withholding',
#     'contract_multic_fix',
#     'account_invoice_pricelist_discount',
#     'account_invoice_report_partner_categ',
#     'account_invoice_tax_auto_update',
#     'account_sale_different_currency',
#     'account_journal_payment_subtype',
#     'account_voucher_contact',
#     'account_voucher_fix',
#     'account_voucher_manual_reconcile',
#     'account_voucher_payline',
#     'account_voucher_popup_print',
#     'account_voucher_account_fix',
#     'account_voucher_constraint',
#     'account_voucher_double_validation',
#     'account_voucher_multic_fix',
#     'crm_partner_history',
#     'crm_phonecall_extend',
#     'crm_phonecall_type',
#     'hr_sign_in_out_task',
#     'hr_timesheet_project',
#     'mrp_auto_prod',
#     'calendar_done',
#     'calendar_state',
#     'mass_mailing_keep_archives',
#     'l10n_ar_account_voucher',
#     'l10n_ar_aeroo_receipt',
#     'l10n_ar_base_vat',
#     'l10n_ar_hide_receipts',
#     'l10n_ar_invoice_receipt',
#     'l10n_ar_account_check',
#     'infrastructure_product',
#     'auth_server_admin_passwd_passkey',
#     'collector_test',
#     'web_fixed_headers',
#     'web_hw_collector',
#     'web_list_view_sticky',
#     'web_menu_hide',
#     'partner_employee',
#     'partner_establishment',
#     'partner_no_auto_search',
#     'partner_search_by_ref',
#     'partner_search_by_vat',
#     'partner_source',
#     'partner_vat_unique',
#     'partner_views_fields_base_vat',
#     'user_partner_is_employee',
#     'product_uom_prices',
#     'product_publichsed_sale_price',
#     'product_uom_prices_currency',
#     'product_force_create_variants',
#     'product_no_auto_search',
#     'product_pack_pos',
#     'product_stock_location',
#     'product_template_update_active',
#     'sale_stock_product_sale_uom',
#     'portal_project_issue_solutions',
#     'project_issue_views_modifications',
#     'project_long_term',
#     'project_task_desc_html',
#     'project_user_story',
#     'portal_project_issue_create',
#     'project_analytic_integration',
#     'project_task_delegate',
#     'project_task_order',
#     'purchase_add_products_wizard',
#     'purchase_ref_editable',
#     'report_extended_voucher',
#     'web_pdf_preview',
#     'sale_pricelist_discount',
#     'sales_to_sale_order',
#     'sale_team_group',
#     'sale_multic_fix',
#     'stock_multic_fix',
#     'stock_picking_locations',
#     'stock_move_defaults',
#     'stock_picking_driver',
#     'stock_transfer_set_zero',
#     'stock_transfer_lot_filter',
#     'website_less',
#     'website_portal_sale_taxes_included',
#     'website_rate_product',
#     'website_remove_product_legend',
#     'website_sale_cart_preview_taxes_included',
#     'website_sale_invoice_before_delivery',
#     'website_search',
#     'website_tracking',
#     'web_snippet_extra',
#     'l10n_ar_chart_generic_tax_settlement',
#     'l10n_ar_chart_generic_withholding',
# ]
